# -*- coding: utf-8 -*-
"""svm_sh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iydWZxakw1JuPXhxQR0w6aK4KdLGxSvh
"""

#!/bin/bash
#$ -q all.q
#$ -cwd
module load Python/3.7.2
python3 -m pip install sklearn

python3 script_modelo_teste_linear.py  /Storage/data1/nina.pinheiro/iniciacao/HCKmer/projeto/bbmap_high/out_original_bbmap/bbmap_high_original.fq  /Storage/data1/nina.pinheiro/iniciacao/HC$$cao/HCKmer/projeto/bbmap_high/out_mutado_reads_bbmap_/bbmap_high_1/bbmap_high_1.fq 7 report_teste__7_linear_txt