# -*- coding: utf-8 -*-
"""histograma_color_bbmap_high.sh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K491TApgZ3PL9ryUJp6rQWbpXrPbVhON
"""

#!/bin/bash
#$ -q all.q
#$ -cwd
#$ -t 1-10
module load Python/3.7.2
mut_input_r1=`ls -1 /Storage/data1/nina.pinheiro/iniciacao/HCKmer/projeto/bbmap_high/out_mutado_reads_bbmap_/bbmap_high_${SGE_TASK_ID}/bbmap_high_${SGE_TASK_ID}.fq`

python3 histograma_color_bbmapp.py   -F /Storage/data1/nina.pinheiro/iniciacao/HCKmer/projeto/bbmap_high/out_original_bbmap/bbmap_high_original.fq  -M $mut_input_r1 -O /Storage/data1/nina.$