# -*- coding: utf-8 -*-
"""kat_density_matrix_bbmap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K491TApgZ3PL9ryUJp6rQWbpXrPbVhON
"""

Arquivo: kat_density_matrix_bbmap.sh

#!/bin/bash
#$ -q all.q
#$ -cwd
#$ -t 1-10

module load miniconda3
export PATH="/Storage/data1/felipe.peres/src/KAT/bin/:$PATH"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/Storage/data1/felipe.peres/src/libtool-2.4.6/bin/:/Storage/data1/felipe.peres/src/KAT/deps/boost/build/lib/:/Storage/progs/miniconda3/lib/

matrix=`ls -1 /Storage/data1/nina.pinheiro/iniciacao/HCKmer/projeto/kat_bbmap_katkmers_7_${SGE_TASK_ID}.fq-main.mx`


kat plot density -o /Storage/data1/nina.pinheiro/iniciacao/HCKmer/projeto/kat_kmers/kat_density_bbmap_katkmers_7_${SGE_TASK_ID}  $matrix