# -*- coding: utf-8 -*-
"""kat-bbmpa-gc-original.sh .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K491TApgZ3PL9ryUJp6rQWbpXrPbVhON
"""

#!/bin/bash
#$ -q all.q
#$ -cwd
#$ -pe smp 4
module load miniconda3
export PATH="/Storage/data1/felipe.peres/src/KAT/bin/:$PATH"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/Storage/data1/felipe.peres/src/libtool-2.4.6/bin/:/Storage/data1/felipe.peres/src/KAT/deps/boost/build/lib/:/Storage/progs/miniconda3/lib/

original_input_r1=`ls -1 /Storage/data1/nina.pinheiro/iniciacao/HCKmer/projeto/bbmap_high/out_original_bbmap/bbmap_high_original.fq`

kat gcp -m 4 -o /Storage/data1/nina.pinheiro/iniciacao/HCKmer/projeto/kat_kmers/saidas_gc/kat_bbmap_original_gc_4.fq  -t 4   $original_input_r1